Description: "server stack for CD Exercise"
Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-05b622b5fa0269787
      Tags:
        - Key: Project
          Value: udacity
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access on port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
